# SITE CONFIGURATION
title: Thiago's Blog # your site title
author: Thiago Henrique # You :P
description: > # Meta description of Homepage
  Compartilhando meus conhecimentos sobre Desenvolvimento de Software e Data Science
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://thiagosilva95.github.io/" # the base hostname & protocol for your site, e.g. http://example.com

# SEO PLUGIN
social:
  name: Thiago Henrique Nascimento da Silva
  links:
    - https://www.facebook.com/thiago.henrique.14811
    - https://www.linkedin.com/in/thiagohsilvadev/
    - https://github.com/thiagosilva95

# THEME SETTINGS
navigation: # Navigation links
  - {name: 'Home', link: '/'}
  - {name: 'About', link: '/about'}
  - {name: 'Contact', link: '/contact'}

tagline: >
  Compartilhando meus conhecimentos sobre Desenvolvimento de Software e Data Science

hero_img: posts/sydney4.jpg # Main background image: use the path from /assets/img/ => This will output /assets/img/posts/sleek_lg.jpg

email: thiagonascimento95@hotmail.com # email for form submission

github_username:  thiagosilva95 # replace with your_github_username or comment to remove link from footer
linkedin_username: thiagohsilvadev
facebook_username: thiago.henrique.14811

disqus:
  shortname: thiagosilva95 # to enable comments replace with your_disqus_shortname

# google_tag_manager: GTM-XXXXXXX # Uncomment to enable GTM. Replace GTM-XXXXXXX with your GTM container ID

service_worker: true

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge # or pygments or null
# theme: jekyll-sleek # Uncomment if you're using the theme as a ruby gem
exclude:
  - README.md
  - node_modules
  - script
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log
  - gulpfile.js
  - sleek.jpg

include: ['_pages']
permalink: /:title/

compress_html:
  clippings: all

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
